apiVersion: v1
kind: Service
metadata:
  name: service-downstream
  labels:
    app: service-downstream
spec:
  selector:
    app: service-downstream
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP